services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /opt/docker/nginxproxymanager/data:/data
      - /opt/docker/nginxproxymanager/letsencrypt:/etc/letsencrypt
